connectors:
  matrix:
    mxid: "@bot_spelling_correction:bot.parsi.ai"
    password: "Group1@nlp"
    rooms:
      'main': '#samplebot:bot.parsi.ai'
    homeserver: "https://bot.parsi.ai"
    nick: "bot_spelling_correction"

skills:
  dehkhoda:
    path: correction_skill.py

welcome-message: true